function [p,num] = riskcue_parameters()
%RISK CUE model and default numerical settings. MATLAB R2017b or later.
% Dimensionless mechanism-exploration parameters, not fitted biological data.
p=struct('dP',.05,'dN',.10,'dW',.30,'xi',1,'chi',2.5, ...
 'a',1.5,'h',.6,'b',.8,'delta',.25,'delta1',.20, ...
 'r',1,'r1',1,'gamma',1,'mu',1,'tau',1,'Lx',10,'Ly',10);
num=struct('Nx',100,'Ny',100,'dt',.005,'Tend',120, ...
 'output_dt',.10,'flux','upwind','initial_amplitude',.005,'initial_kind','broadband', ...
 'mode',[4 6],'transverse_seed',0,'CFL_limit',.70, ...
 'negative_tolerance',1e-10,'store_snapshots',false,'snapshot_tail',20,'progress_every',2000, ...
 'correlation_floor',1e-4,'late_fraction',.25);
end
